version: '3'
services:

  unit1:
    image: unit:v2
    container_name: automate1
    restart: always
    environment:
      - unit_id=1
    depends_on:
      - workerServer
    networks:
      - network_usine

  unit2:
    image: unit:v2
    container_name: automate2
    restart: always
    environment:
      - unit_id=2
    depends_on:
      - workerServer
    networks:
      - network_usine

  unit3:
    image: unit:v2
    container_name: automate3
    restart: always
    environment:
      - unit_id=3
    depends_on:
      - workerServer
    networks:
      - network_usine

  unit4:
    image: unit:v2
    container_name: automate4
    restart: always
    environment:
      - unit_id=4
    depends_on:
      - workerServer
    networks:
    - network_usine

  unit5:
    image: unit:v2
    container_name: automate5
    restart: always
    environment:
      - unit_id=5
    depends_on:
      - workerServer
    networks:
      - network_usine

  workerServer:
    image: workerserver:v2
    container_name: workerServer
    restart: always
    hostname: "workerserver"
    networks:
     network_usine:
        ipv4_address: 192.168.0.10

networks:
  network_usine:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24