version: '3'
services:

  unit1:
    image: unit:v1
    container_name: automate1
    restart: always
    environment:
      - unit_id=1
    depends_on:
      - workerServer

  unit2:
    image: unit:v1
    container_name: automate2
    restart: always
    environment:
      - unit_id=2
    depends_on:
      - workerServer

  unit3:
    image: unit:v1
    container_name: automate3
    restart: always
    environment:
      - unit_id=3
    depends_on:
      - workerServer

  unit4:
    image: unit:v1
    container_name: automate4
    restart: always
    environment:
      - unit_id=4
    depends_on:
      - workerServer

  unit5:
    image: unit:v1
    container_name: automate5
    restart: always
    environment:
      - unit_id=5
    depends_on:
      - workerServer

  workerServer:
    image: workerserver:v1
    container_name: workerServer
    restart: always
    hostname: "workerserver"

